### ISSUE TITLE
Reference trajectories

### ISSUE THREAD

**Issue by Dcasadoherraez** [snail-radar/dataset_tools#3]
Hello!
Thanks so much for this nice dataset! It seems really well organized and the data seems good so far :)
I have one question regarding the reference trajectories.

This is a plot of all the `tls_T_xt32.txt` files in `ref_trajs`. 
![image](https://github.com/user-attachments/assets/ba753749-4b6d-40d9-9924-245f9934e68f)

Those plots seem to only belong to this region of the campus:
![image](https://github.com/user-attachments/assets/df8f1b96-98d8-4195-a8d8-7f24ccbb129a)

Meanwhile, the info arts and eng. and the info arts faculties don't belong to these paths:
![image](https://github.com/user-attachments/assets/8fa276df-1662-46c6-8dd8-92b7454aba0e)

I guess the missing parts of the long trajectories are due to this statement:
_''For large-scale sequences, since the TLS map only covers the beginning and end parts of the sequence, we generate the reference trajectory only for the beginning and end subsequences within the TLS coverage, as done in TUM-VI [Schubert et al., 2018](https://snail-radar.github.io/docs/groundtruth.html#schubert2018).''_

Using `utm50r_T_x36dimu.txt` does return the entire trajectory of the sequence
![image](https://github.com/user-attachments/assets/04873eb2-95d7-4eb7-8a83-ddb2d07cdceb)

Do you suggest any method for evaluation based on `tls_T_xt32.txt`, without having the entire ground truth trajectory? Have you noticed any variations in accuracy compared to `utm50r_T_x36dimu.txt`?

Thanks in advance!!!!

**Comment by JzHuai0108** [comment]
Thank you for your interest and viz effort in our dataset.

Indeed our accurate reference trajectories only cover the campus area due to the limited TLS coverage. For the accuracy evaluation with tls_T_xt32.txt, the classic ATE RMSE can be used as implemented in [rpj_traj_eval_tool](https://github.com/uzh-rpg/rpg_trajectory_evaluation) since it does not require a small time gap between consecutive poses. 
We provide the utm50r_T_x36dimu.txt for the purpose of place recognition which usually does not require accurate height values. 
Meanwhile, we are working to provide the complete trajectories by fusing the TLS trajectories, lidar odometry, and the GNSS trajectories with a pose graph optimizer. It should be ready in one week, Aug 25 2024. But we only guarantee the visual quality of these trajectories :), and their suitability for place recognition.

**Comment by ChiyunNoh** [comment]
Hello author! @JzHuai0108 
Has the revised gt-trajectory been uploaded?
If it hasn't been uploaded yet, could you mention me when it has been uploaded?

**Comment by JzHuai0108** [comment]
Thank you for your interest. I am tuning the least squares solver that fuses the odometry data.
The fused solution should be ready in two or three days. I will leave a message here when it is ready to download.

**Comment by Dcasadoherraez** [comment]
As a small feedback it would be amazing if you also provide them in kitti format directly.

**Comment by JzHuai0108** [comment]
Hi @Dcasadoherraez , Ok, I will do accordingly. Note in the KITTI format each line has 12 numbers of the first 3 lines of the 4X4 transformation matrix, we have to provide the times in another file.

**Comment by JzHuai0108** [comment]
Hi friends, 
I have completed the full trajectories by PGO.
They are [here](https://1drv.ms/u/c/60208caf9367dbb1/EcocK5z8cYdHg2l0MG1EbZ4BtjuJaHhtHLtSM2IsCG44OQ?e=UfS6NX).
Note the full trajectory has large uncertainties in z within 1 meter as shown in the below quality check images, also see the readme.md inside the zip.
So the full trajs are good enough for place recognition training and testing, but not intended for odometry quality benchmarking. 

![horizontal_quality_check](https://github.com/user-attachments/assets/19e92a8b-dbb8-4869-b434-85b71a44ea6d)
![vertical_quality_check](https://github.com/user-attachments/assets/2a1ac0ce-7e50-47b3-91cc-418b6427fb98)

**Comment by Dcasadoherraez** [comment]
Thanks so much for your effort providing the best data possible! Really appreciate that.
Certainly the uncertainty might be a problem for odometry/slam. But at least it can provide some baseline for comparison between methods. 

Thanks again! 

I will close the issue and reopen if I notice anything weird :D
